### ISSUE TITLE
error when importing metadata

### ISSUE THREAD

**Issue by alecristia** [LAAC-LSCP/ChildProject#197]
I've taken [metadata.py from lyon in EL1000](https://gin.g-node.org/EL1000/lyon/src/main/scripts/import.py)

Reading the arguments at the top, I've decided the command I need to issue is:

`python scripts/metadata.py rague metadata/confidential/original --recompute-ages`

(the following error arises with or without --recompute-ages)

I get an error:

> Traceback (most recent call last):
  File "scripts/metadata.py", line 34, in <module>
    children = pd.read_csv(args.metadata, dtype = {'child_id': str})
  File "/Users/acristia/ChildProjectVenv/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/acristia/ChildProjectVenv/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/Users/acristia/ChildProjectVenv/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/Users/acristia/ChildProjectVenv/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/acristia/ChildProjectVenv/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 537, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 711, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

I looked at the csv -- it doesn't have weird end of lines, and it's a true csv (so no need to specify ", sep = ';'" as in [Elo](https://gin.g-node.org/EL1000/elo/src/main/scripts/metadata.py). Looking at other metadata.py also doesn't give me ideas as to what may be wrong in my case.

And to make things more interesting, the previous version of metadata.py I was using was reading that same csv metadata without complaining. Any ideas?

**Comment by lucasgautheron** [comment]
The second argument of metadata.py should be the path of the original CSV, not its directory, so replace:

```
python scripts/metadata.py rague metadata/confidential/original
```

with:

```
python scripts/metadata.py rague metadata/confidential/original/purdue_ndd_metadata.csv
```

And it should work
