### ISSUE TITLE
Sampler issue under Windows

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildProject#253]
**Is your feature request related to a problem? Please describe.**

```bash
$ child-project sampler align-vandam/inputs/vandam-data/ sampler/ high-volubility --annotation-set CHA --metric awc --windows-length 60000 --windows-count 5
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "c:\users\apfelsaft\python\python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\users\apfelsaft\python\python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\apfelsaft\python\python38\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "c:\users\apfelsaft\python\python38\lib\multiprocessing\queues.py", line 358, in get
    return _ForkingPickler.loads(res)
  File "c:\users\apfelsaft\python\python38\lib\site-packages\ChildProject\pipelines\__init__.py", line 1, in <module>
    from .samplers import SamplerPipeline
  File "c:\users\apfelsaft\python\python38\lib\site-packages\ChildProject\pipelines\samplers.py", line 17, in <module>
    class Sampler(ABC):
  File "c:\users\apfelsaft\python\python38\lib\site-packages\ChildProject\pipelines\samplers.py", line 19, in Sampler
    project: ChildProject.projects.ChildProject,
AttributeError: module 'ChildProject' has no attribute 'projects'
```

**Comment by alecristia** [comment]
we checked today and realized there's no test that checks specifically high-vol sampling, should it be added?
