### ISSUE TITLE
ChildProject installation problem on MacOs 10.15.7 / Python 3.8.2 / conda env for ChildProject only

### ISSUE THREAD

**Issue by orasanen** [LAAC-LSCP/ChildProject#281]
After finalizing installation according to instructions here https://childproject.readthedocs.io/en/latest/install.html , I get the following error when trying to check installation functionality: 

Successfully installed ChildProject-0.0.1 MarkupSafe-2.0.1 PyYAML-5.4.1 audioread-2.1.9 click-8.0.1 colorama-0.4.4 cycler-0.10.0 decorator-5.1.0 docopt-0.6.2 idna-2.10 importlib-resources-5.2.2 jinja2-3.0.1 joblib-1.0.1 kiwisolver-1.3.2 librosa-0.8.1 llvmlite-0.37.0 lxml-4.6.3 matplotlib-3.4.3 mpmath-1.2.1 nltk-3.6.2 numba-0.54.0 numpy-1.21.2 packaging-21.0 pandas-1.3.3 panoptes-client-1.4.0 pillow-8.3.2 pooch-1.5.1 pyannote.core-4.1 pyannote.database-4.1.1 pyannote.metrics-3.0.1 pydub-0.25.1 pylangacq-0.15.0 pympi-ling-1.70.2 pyparsing-2.4.7 pysoundfile-0.9.0.post1 python-dateutil-2.8.2 python-magic-0.4.24 pytz-2021.1 redo-2.0.4 regex-2021.8.28 requests-2.25.0 resampy-0.2.2 scikit-learn-0.24.2 scipy-1.7.1 shellingham-1.4.0 sklearn-0.0 sortedcontainers-2.4.0 soundfile-0.10.3.post1 sox-1.4.1 sympy-1.8 tabulate-0.8.9 threadpoolctl-2.2.0 typer-0.4.0 typing-extensions-3.10.0.2
WARNING: You are using pip version 19.2.3, however version 21.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

-->

ChildProject) wks-86206-mac:dists rasaneno$ child-project --help
/Library/Python/3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/local/bin/child-project", line 6, in <module>
    from ChildProject.cmdline import main
  File "/Library/Python/3.8/site-packages/ChildProject/cmdline.py", line 4, in <module>
    from ChildProject.pipelines import *
  File "/Library/Python/3.8/site-packages/ChildProject/pipelines/__init__.py", line 3, in <module>
    from .zooniverse import ZooniversePipeline
  File "/Library/Python/3.8/site-packages/ChildProject/pipelines/zooniverse.py", line 9, in <module>
    from panoptes_client import Panoptes, Project, Subject, SubjectSet, Classification
  File "/Library/Python/3.8/site-packages/panoptes_client/__init__.py", line 1, in <module>
    from panoptes_client.classification import Classification
  File "/Library/Python/3.8/site-packages/panoptes_client/classification.py", line 3, in <module>
    from panoptes_client.panoptes import LinkResolver, PanoptesObject
  File "/Library/Python/3.8/site-packages/panoptes_client/panoptes.py", line 25, in <module>
    class Panoptes(object):
  File "/Library/Python/3.8/site-packages/panoptes_client/panoptes.py", line 58, in Panoptes
    'User-Agent': 'panoptes-python-client/version=' + pkg_resources.require('panoptes_client')[0].version
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (chardet 4.0.0 (/Library/Python/3.8/site-packages), Requirement.parse('chardet<4,>=3.0.2'), {'requests'})

**Comment by lucasgautheron** [comment]
I would suggest to issue the following command:

```bash
pip install "chardet<4,>=3.0.2" --upgrade
```

And then try again!

**Comment by lucasgautheron** [comment]
The last two commits should have fixed it by enforcing version constraints on some dependencies.
This should work now:

```bash
pip3 uninstall chardet
pip3 install git+https://github.com/LAAC-LSCP/ChildProject.git --upgrade
```

**Comment by orasanen** [comment]
Thanks, this resolved the issue.
