### ISSUE TITLE
making installation instructions more newbie friendly

### ISSUE THREAD

**Issue by alecristia** [LAAC-LSCP/ChildProject#416]
**Is your feature request related to a problem? Please describe.**

Two similar & related problems:

- If one directly clicks on eg macos installation, one skips the important Note about conda installation
- Neither the note nor the macos installation instructions holds one hand to understand that output like the following means conda isn't installed:

`conda env create -f env.yml`

> Traceback (most recent call last):
  File "/Users/acristia/opt/miniconda2/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/Users/acristia/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 149, in main
    from ..exceptions import conda_exception_handler
  File "/Users/acristia/opt/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 19, in <module>
    from ._vendor.auxlib.entity import EntityEncoder
  File "/Users/acristia/opt/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 253, in <module>
    from .collection import AttrDict, frozendict, make_immutable
  File "/Users/acristia/opt/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/collection.py", line 10, in <module>
    from .compat import isiterable, iteritems, odict, text_type
  File "/Users/acristia/opt/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/compat.py", line 10, in <module>
    from ._vendor.five import WhateverIO as StringIO, with_metaclass
  File "/Users/acristia/opt/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/_vendor/five.py", line 80, in <module>
    absolute_to_nanoseconds = CoreServices.AbsoluteToNanoseconds
  File "/Users/acristia/opt/miniconda2/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/Users/acristia/opt/miniconda2/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found

` conda --version`

> Traceback (most recent call last):
  File "/Users/acristia/opt/miniconda2/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/Users/acristia/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 149, in main
    from ..exceptions import conda_exception_handler
  File "/Users/acristia/opt/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 19, in <module>
    from ._vendor.auxlib.entity import EntityEncoder
  File "/Users/acristia/opt/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 253, in <module>
    from .collection import AttrDict, frozendict, make_immutable
  File "/Users/acristia/opt/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/collection.py", line 10, in <module>
    from .compat import isiterable, iteritems, odict, text_type
  File "/Users/acristia/opt/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/compat.py", line 10, in <module>
    from ._vendor.five import WhateverIO as StringIO, with_metaclass
  File "/Users/acristia/opt/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/_vendor/five.py", line 80, in <module>
    absolute_to_nanoseconds = CoreServices.AbsoluteToNanoseconds
  File "/Users/acristia/opt/miniconda2/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/Users/acristia/opt/miniconda2/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found

**Describe the solution you'd like**
Perhaps just adding something like the following "if you get any error, it probably means conda isn't installed" with a link to the conda install instructions

**Comment by LoannPeurey** [comment]
Revisit this in September

**Comment by alecristia** [comment]
It's true that instructions could be improved. However, we think that installation instructions for complete newbies would require rehauling. Also, true newbies that would not find their way out of these errors may be served by echolalia. Revisit post-echolalia
