### ISSUE TITLE
Annotation importation dataframe has a "duration" column

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildProject#479]
Will notably happen with the EL1000 importer: https://gin.g-node.org/LAAC-LSCP/tools/src/master/EL1000/annotations.py

Error is:

```python
Traceback (most recent call last):
  File "/home/lgautheron/.conda/envs/stan/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'duration'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch2/lgautheron/data/kidd-vtc/scripts/import_vtc.py", line 14, in <module>
    importer.process(
  File "/home/lgautheron/.conda/envs/stan/lib/python3.12/site-packages/EL1000/annotations.py", line 66, in process
    self.am.import_annotations(input, threads = threads)
  File "/home/lgautheron/.conda/envs/stan/lib/python3.12/site-packages/ChildProject/annotations.py", line 634, in import_annotations
    assert (input_processed["range_offset"] <= input_processed.merge(self.project.recordings,
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lgautheron/.conda/envs/stan/lib/python3.12/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lgautheron/.conda/envs/stan/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'duration'
```

This is probably because of performing a merge on dataframes with duplicate columns.

**Comment by LoannPeurey** [comment]
b63e15af91
